SPACING_XS = 8
SPACING_SM = 10
SPACING_MD = 12
SPACING_LG = 14
SPACING_XL = 16
SPACING_XXL = 20

FONT_SCREEN_TITLE = 22
FONT_HEADING = 20
FONT_SUBHEADING = 15
FONT_CAPTION = 13

# Alturas de linha / rótulos
LINE_LABEL = 22
LINE_TITLE = 36
LINE_SUBTITLE = 40
LINE_HEADING = 40
TEXT_BLOCK_TWO_LINES = 60

INPUT_HEIGHT = 40
INPUT_HEIGHT_COMFY = 42
BUTTON_PRIMARY_HEIGHT = 48
BUTTON_SECONDARY_HEIGHT = 44
BUTTON_ROW_HEIGHT = 48

TOAST_PADDING = 12
TOAST_SPACING = 8
TOAST_MESSAGE_WIDTH = 280
TOAST_BUTTON_HEIGHT = 44
TOAST_POPUP_HEIGHT = 200
TOAST_WIDTH_HINT = 0.85
